spring.application.name=app-peluqueria

spring.datasource.url=jdbc:postgresql://localhost:5432/turnosapp_db
spring.datasource.username=postgres
spring.datasource.password=46660714Facu
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true